"""add line_items column

Revision ID: e26bc1684c69
Revises: 
Create Date: 2026-06-30 17:27:02.979857

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e26bc1684c69'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('declarations', sa.Column('line_items', sa.JSON(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('declarations', 'line_items')
    # ### end Alembic commands ###
